// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.ArtistRepository;
import meg.biblio.catalog.db.dao.ArtistDaoDataOnDemand;
import meg.biblio.catalog.db.dao.ArtistDaoIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ArtistDaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ArtistDaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ArtistDaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ArtistDaoIntegrationTest: @Transactional;
    
    @Autowired
    ArtistDaoDataOnDemand ArtistDaoIntegrationTest.dod;
    
    @Autowired
    ArtistRepository ArtistDaoIntegrationTest.artistRepository;
    
    @Test
    public void ArtistDaoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to initialize correctly", dod.getRandomArtistDao());
        long count = artistRepository.count();
        Assert.assertTrue("Counter for 'ArtistDao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ArtistDaoIntegrationTest.testFind() {
        ArtistDao obj = dod.getRandomArtistDao();
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to provide an identifier", id);
        obj = artistRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ArtistDao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ArtistDao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ArtistDaoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to initialize correctly", dod.getRandomArtistDao());
        long count = artistRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ArtistDao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ArtistDao> result = artistRepository.findAll();
        Assert.assertNotNull("Find all method for 'ArtistDao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ArtistDao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ArtistDaoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to initialize correctly", dod.getRandomArtistDao());
        long count = artistRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ArtistDao> result = artistRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ArtistDao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ArtistDao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ArtistDaoIntegrationTest.testFlush() {
        ArtistDao obj = dod.getRandomArtistDao();
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to provide an identifier", id);
        obj = artistRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ArtistDao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyArtistDao(obj);
        Integer currentVersion = obj.getVersion();
        artistRepository.flush();
        Assert.assertTrue("Version for 'ArtistDao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ArtistDaoIntegrationTest.testSaveUpdate() {
        ArtistDao obj = dod.getRandomArtistDao();
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to provide an identifier", id);
        obj = artistRepository.findOne(id);
        boolean modified =  dod.modifyArtistDao(obj);
        Integer currentVersion = obj.getVersion();
        ArtistDao merged = artistRepository.save(obj);
        artistRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ArtistDao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ArtistDaoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to initialize correctly", dod.getRandomArtistDao());
        ArtistDao obj = dod.getNewTransientArtistDao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ArtistDao' identifier to be null", obj.getId());
        try {
            artistRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        artistRepository.flush();
        Assert.assertNotNull("Expected 'ArtistDao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ArtistDaoIntegrationTest.testDelete() {
        ArtistDao obj = dod.getRandomArtistDao();
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ArtistDao' failed to provide an identifier", id);
        obj = artistRepository.findOne(id);
        artistRepository.delete(obj);
        artistRepository.flush();
        Assert.assertNull("Failed to remove 'ArtistDao' with identifier '" + id + "'", artistRepository.findOne(id));
    }
    
}
