// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.ArtistRepository;
import meg.biblio.catalog.db.dao.ArtistDao;
import meg.biblio.catalog.db.dao.ArtistDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ArtistDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ArtistDaoDataOnDemand: @Component;
    
    private Random ArtistDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<ArtistDao> ArtistDaoDataOnDemand.data;
    
    @Autowired
    ArtistRepository ArtistDaoDataOnDemand.artistRepository;
    
    public ArtistDao ArtistDaoDataOnDemand.getNewTransientArtistDao(int index) {
        ArtistDao obj = new ArtistDao();
        setFirstname(obj, index);
        setLastname(obj, index);
        setMiddlename(obj, index);
        return obj;
    }
    
    public void ArtistDaoDataOnDemand.setFirstname(ArtistDao obj, int index) {
        String firstname = "firstname_" + index;
        obj.setFirstname(firstname);
    }
    
    public void ArtistDaoDataOnDemand.setLastname(ArtistDao obj, int index) {
        String lastname = "lastname_" + index;
        obj.setLastname(lastname);
    }
    
    public void ArtistDaoDataOnDemand.setMiddlename(ArtistDao obj, int index) {
        String middlename = "middlename_" + index;
        obj.setMiddlename(middlename);
    }
    
    public ArtistDao ArtistDaoDataOnDemand.getSpecificArtistDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ArtistDao obj = data.get(index);
        Long id = obj.getId();
        return artistRepository.findOne(id);
    }
    
    public ArtistDao ArtistDaoDataOnDemand.getRandomArtistDao() {
        init();
        ArtistDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return artistRepository.findOne(id);
    }
    
    public boolean ArtistDaoDataOnDemand.modifyArtistDao(ArtistDao obj) {
        return false;
    }
    
    public void ArtistDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = artistRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ArtistDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ArtistDao>();
        for (int i = 0; i < 10; i++) {
            ArtistDao obj = getNewTransientArtistDao(i);
            try {
                artistRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            artistRepository.flush();
            data.add(obj);
        }
    }
    
}
