// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.BookRepository;
import meg.biblio.catalog.db.dao.BookDao;
import meg.biblio.catalog.db.dao.BookDaoDataOnDemand;
import meg.biblio.catalog.db.dao.BookDetailDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BookDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BookDaoDataOnDemand: @Component;
    
    private Random BookDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<BookDao> BookDaoDataOnDemand.data;
    
    @Autowired
    BookDetailDaoDataOnDemand BookDaoDataOnDemand.bookDetailDaoDataOnDemand;
    
    @Autowired
    BookRepository BookDaoDataOnDemand.bookRepository;
    
    public BookDao BookDaoDataOnDemand.getNewTransientBookDao(int index) {
        BookDao obj = new BookDao();
        setBarcodeid(obj, index);
        setClientbookid(obj, index);
        setClientbookidsort(obj, index);
        setClientbooktype(obj, index);
        setClientid(obj, index);
        setClientshelfclass(obj, index);
        setClientshelfcode(obj, index);
        setCreatedon(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void BookDaoDataOnDemand.setBarcodeid(BookDao obj, int index) {
        String barcodeid = "barcodeid_" + index;
        obj.setBarcodeid(barcodeid);
    }
    
    public void BookDaoDataOnDemand.setClientbookid(BookDao obj, int index) {
        String clientbookid = "clientbookid_" + index;
        obj.setClientbookid(clientbookid);
    }
    
    public void BookDaoDataOnDemand.setClientbookidsort(BookDao obj, int index) {
        Long clientbookidsort = new Integer(index).longValue();
        obj.setClientbookidsort(clientbookidsort);
    }
    
    public void BookDaoDataOnDemand.setClientbooktype(BookDao obj, int index) {
        Long clientbooktype = new Integer(index).longValue();
        obj.setClientbooktype(clientbooktype);
    }
    
    public void BookDaoDataOnDemand.setClientid(BookDao obj, int index) {
        Long clientid = new Integer(index).longValue();
        obj.setClientid(clientid);
    }
    
    public void BookDaoDataOnDemand.setClientshelfclass(BookDao obj, int index) {
        String clientshelfclass = "clientshelfclass_" + index;
        obj.setClientshelfclass(clientshelfclass);
    }
    
    public void BookDaoDataOnDemand.setClientshelfcode(BookDao obj, int index) {
        Long clientshelfcode = new Integer(index).longValue();
        obj.setClientshelfcode(clientshelfcode);
    }
    
    public void BookDaoDataOnDemand.setCreatedon(BookDao obj, int index) {
        Date createdon = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedon(createdon);
    }
    
    public void BookDaoDataOnDemand.setStatus(BookDao obj, int index) {
        Long status = new Integer(index).longValue();
        obj.setStatus(status);
    }
    
    public BookDao BookDaoDataOnDemand.getSpecificBookDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BookDao obj = data.get(index);
        Long id = obj.getId();
        return bookRepository.findOne(id);
    }
    
    public BookDao BookDaoDataOnDemand.getRandomBookDao() {
        init();
        BookDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return bookRepository.findOne(id);
    }
    
    public boolean BookDaoDataOnDemand.modifyBookDao(BookDao obj) {
        return false;
    }
    
    public void BookDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = bookRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BookDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BookDao>();
        for (int i = 0; i < 10; i++) {
            BookDao obj = getNewTransientBookDao(i);
            try {
                bookRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            bookRepository.flush();
            data.add(obj);
        }
    }
    
}
