// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.BookRepository;
import meg.biblio.catalog.db.dao.BookDao;
import meg.biblio.catalog.db.dao.BookDaoDataOnDemand;
import meg.biblio.catalog.db.dao.PublisherDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BookDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BookDaoDataOnDemand: @Component;
    
    private Random BookDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<BookDao> BookDaoDataOnDemand.data;
    
    @Autowired
    PublisherDaoDataOnDemand BookDaoDataOnDemand.publisherDaoDataOnDemand;
    
    @Autowired
    BookRepository BookDaoDataOnDemand.bookRepository;
    
    public BookDao BookDaoDataOnDemand.getNewTransientBookDao(int index) {
        BookDao obj = new BookDao();
        setClientbookid(obj, index);
        setClientbookidsort(obj, index);
        setClientid(obj, index);
        setCreatedon(obj, index);
        setDescription(obj, index);
        setDetailstatus(obj, index);
        setIsbn10(obj, index);
        setIsbn13(obj, index);
        setLanguage(obj, index);
        setPublishyear(obj, index);
        setShelfclass(obj, index);
        setShelfclassverified(obj, index);
        setStatus(obj, index);
        setTitle(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void BookDaoDataOnDemand.setClientbookid(BookDao obj, int index) {
        String clientbookid = "clientbookid_" + index;
        obj.setClientbookid(clientbookid);
    }
    
    public void BookDaoDataOnDemand.setClientbookidsort(BookDao obj, int index) {
        Long clientbookidsort = new Integer(index).longValue();
        obj.setClientbookidsort(clientbookidsort);
    }
    
    public void BookDaoDataOnDemand.setClientid(BookDao obj, int index) {
        Long clientid = new Integer(index).longValue();
        obj.setClientid(clientid);
    }
    
    public void BookDaoDataOnDemand.setCreatedon(BookDao obj, int index) {
        Date createdon = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedon(createdon);
    }
    
    public void BookDaoDataOnDemand.setDescription(BookDao obj, int index) {
        String description = "description_" + index;
        if (description.length() > 1512) {
            description = description.substring(0, 1512);
        }
        obj.setDescription(description);
    }
    
    public void BookDaoDataOnDemand.setDetailstatus(BookDao obj, int index) {
        Long detailstatus = new Integer(index).longValue();
        obj.setDetailstatus(detailstatus);
    }
    
    public void BookDaoDataOnDemand.setIsbn10(BookDao obj, int index) {
        String isbn10 = "isbn10_" + index;
        obj.setIsbn10(isbn10);
    }
    
    public void BookDaoDataOnDemand.setIsbn13(BookDao obj, int index) {
        String isbn13 = "isbn13_" + index;
        obj.setIsbn13(isbn13);
    }
    
    public void BookDaoDataOnDemand.setLanguage(BookDao obj, int index) {
        String language = "language_" + index;
        obj.setLanguage(language);
    }
    
    public void BookDaoDataOnDemand.setPublishyear(BookDao obj, int index) {
        Long publishyear = new Integer(index).longValue();
        obj.setPublishyear(publishyear);
    }
    
    public void BookDaoDataOnDemand.setShelfclass(BookDao obj, int index) {
        Long shelfclass = new Integer(index).longValue();
        obj.setShelfclass(shelfclass);
    }
    
    public void BookDaoDataOnDemand.setShelfclassverified(BookDao obj, int index) {
        Boolean shelfclassverified = Boolean.TRUE;
        obj.setShelfclassverified(shelfclassverified);
    }
    
    public void BookDaoDataOnDemand.setStatus(BookDao obj, int index) {
        Long status = new Integer(index).longValue();
        obj.setStatus(status);
    }
    
    public void BookDaoDataOnDemand.setTitle(BookDao obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public void BookDaoDataOnDemand.setType(BookDao obj, int index) {
        Long type = new Integer(index).longValue();
        obj.setType(type);
    }
    
    public BookDao BookDaoDataOnDemand.getSpecificBookDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BookDao obj = data.get(index);
        Long id = obj.getId();
        return bookRepository.findOne(id);
    }
    
    public BookDao BookDaoDataOnDemand.getRandomBookDao() {
        init();
        BookDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return bookRepository.findOne(id);
    }
    
    public boolean BookDaoDataOnDemand.modifyBookDao(BookDao obj) {
        return false;
    }
    
    public void BookDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = bookRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BookDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BookDao>();
        for (int i = 0; i < 10; i++) {
            BookDao obj = getNewTransientBookDao(i);
            try {
                bookRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            bookRepository.flush();
            data.add(obj);
        }
    }
    
}
