// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.ClassificationRepository;
import meg.biblio.catalog.db.dao.ClassificationDao;
import meg.biblio.catalog.db.dao.ClassificationDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ClassificationDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClassificationDaoDataOnDemand: @Component;
    
    private Random ClassificationDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<ClassificationDao> ClassificationDaoDataOnDemand.data;
    
    @Autowired
    ClassificationRepository ClassificationDaoDataOnDemand.classificationRepository;
    
    public ClassificationDao ClassificationDaoDataOnDemand.getNewTransientClassificationDao(int index) {
        ClassificationDao obj = new ClassificationDao();
        setClientid(obj, index);
        setDescription(obj, index);
        setDisplay(obj, index);
        return obj;
    }
    
    public void ClassificationDaoDataOnDemand.setClientid(ClassificationDao obj, int index) {
        Long clientid = new Integer(index).longValue();
        obj.setClientid(clientid);
    }
    
    public void ClassificationDaoDataOnDemand.setDescription(ClassificationDao obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void ClassificationDaoDataOnDemand.setDisplay(ClassificationDao obj, int index) {
        String display = "display_" + index;
        obj.setDisplay(display);
    }
    
    public ClassificationDao ClassificationDaoDataOnDemand.getSpecificClassificationDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ClassificationDao obj = data.get(index);
        Long id = obj.getId();
        return classificationRepository.findOne(id);
    }
    
    public ClassificationDao ClassificationDaoDataOnDemand.getRandomClassificationDao() {
        init();
        ClassificationDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return classificationRepository.findOne(id);
    }
    
    public boolean ClassificationDaoDataOnDemand.modifyClassificationDao(ClassificationDao obj) {
        return false;
    }
    
    public void ClassificationDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = classificationRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ClassificationDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ClassificationDao>();
        for (int i = 0; i < 10; i++) {
            ClassificationDao obj = getNewTransientClassificationDao(i);
            try {
                classificationRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            classificationRepository.flush();
            data.add(obj);
        }
    }
    
}
