// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import meg.biblio.catalog.db.dao.ClassificationDaoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ClassificationDaoIntegrationTest_Roo_Configurable {
    
    declare @type: ClassificationDaoIntegrationTest: @Configurable;
    
}
