// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.ClassificationRepository;
import meg.biblio.catalog.db.dao.ClassificationDaoDataOnDemand;
import meg.biblio.catalog.db.dao.ClassificationDaoIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClassificationDaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClassificationDaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClassificationDaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClassificationDaoIntegrationTest: @Transactional;
    
    @Autowired
    ClassificationDaoDataOnDemand ClassificationDaoIntegrationTest.dod;
    
    @Autowired
    ClassificationRepository ClassificationDaoIntegrationTest.classificationRepository;
    
    @Test
    public void ClassificationDaoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to initialize correctly", dod.getRandomClassificationDao());
        long count = classificationRepository.count();
        Assert.assertTrue("Counter for 'ClassificationDao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClassificationDaoIntegrationTest.testFind() {
        ClassificationDao obj = dod.getRandomClassificationDao();
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to provide an identifier", id);
        obj = classificationRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ClassificationDao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ClassificationDao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClassificationDaoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to initialize correctly", dod.getRandomClassificationDao());
        long count = classificationRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ClassificationDao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ClassificationDao> result = classificationRepository.findAll();
        Assert.assertNotNull("Find all method for 'ClassificationDao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ClassificationDao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClassificationDaoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to initialize correctly", dod.getRandomClassificationDao());
        long count = classificationRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ClassificationDao> result = classificationRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ClassificationDao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ClassificationDao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClassificationDaoIntegrationTest.testFlush() {
        ClassificationDao obj = dod.getRandomClassificationDao();
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to provide an identifier", id);
        obj = classificationRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ClassificationDao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClassificationDao(obj);
        Integer currentVersion = obj.getVersion();
        classificationRepository.flush();
        Assert.assertTrue("Version for 'ClassificationDao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClassificationDaoIntegrationTest.testSaveUpdate() {
        ClassificationDao obj = dod.getRandomClassificationDao();
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to provide an identifier", id);
        obj = classificationRepository.findOne(id);
        boolean modified =  dod.modifyClassificationDao(obj);
        Integer currentVersion = obj.getVersion();
        ClassificationDao merged = classificationRepository.save(obj);
        classificationRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ClassificationDao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClassificationDaoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to initialize correctly", dod.getRandomClassificationDao());
        ClassificationDao obj = dod.getNewTransientClassificationDao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ClassificationDao' identifier to be null", obj.getId());
        try {
            classificationRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        classificationRepository.flush();
        Assert.assertNotNull("Expected 'ClassificationDao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClassificationDaoIntegrationTest.testDelete() {
        ClassificationDao obj = dod.getRandomClassificationDao();
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassificationDao' failed to provide an identifier", id);
        obj = classificationRepository.findOne(id);
        classificationRepository.delete(obj);
        classificationRepository.flush();
        Assert.assertNull("Failed to remove 'ClassificationDao' with identifier '" + id + "'", classificationRepository.findOne(id));
    }
    
}
