// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.FoundDetailsRepository;
import meg.biblio.catalog.db.dao.FoundDetailsDao;
import meg.biblio.catalog.db.dao.FoundDetailsDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FoundDetailsDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FoundDetailsDaoDataOnDemand: @Component;
    
    private Random FoundDetailsDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<FoundDetailsDao> FoundDetailsDaoDataOnDemand.data;
    
    @Autowired
    FoundDetailsRepository FoundDetailsDaoDataOnDemand.foundDetailsRepository;
    
    public FoundDetailsDao FoundDetailsDaoDataOnDemand.getNewTransientFoundDetailsDao(int index) {
        FoundDetailsDao obj = new FoundDetailsDao();
        setAuthors(obj, index);
        setBookid(obj, index);
        setDescription(obj, index);
        setIllustrators(obj, index);
        setIsbn10(obj, index);
        setIsbn13(obj, index);
        setLanguage(obj, index);
        setPublisher(obj, index);
        setPublishyear(obj, index);
        setSearchserviceid(obj, index);
        setTitle(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void FoundDetailsDaoDataOnDemand.setAuthors(FoundDetailsDao obj, int index) {
        String authors = "authors_" + index;
        obj.setAuthors(authors);
    }
    
    public void FoundDetailsDaoDataOnDemand.setBookid(FoundDetailsDao obj, int index) {
        Long bookid = new Integer(index).longValue();
        obj.setBookid(bookid);
    }
    
    public void FoundDetailsDaoDataOnDemand.setDescription(FoundDetailsDao obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void FoundDetailsDaoDataOnDemand.setIllustrators(FoundDetailsDao obj, int index) {
        String illustrators = "illustrators_" + index;
        obj.setIllustrators(illustrators);
    }
    
    public void FoundDetailsDaoDataOnDemand.setIsbn10(FoundDetailsDao obj, int index) {
        String isbn10 = "isbn10_" + index;
        obj.setIsbn10(isbn10);
    }
    
    public void FoundDetailsDaoDataOnDemand.setIsbn13(FoundDetailsDao obj, int index) {
        String isbn13 = "isbn13_" + index;
        obj.setIsbn13(isbn13);
    }
    
    public void FoundDetailsDaoDataOnDemand.setLanguage(FoundDetailsDao obj, int index) {
        String language = "language_" + index;
        obj.setLanguage(language);
    }
    
    public void FoundDetailsDaoDataOnDemand.setPublisher(FoundDetailsDao obj, int index) {
        String publisher = "publisher_" + index;
        obj.setPublisher(publisher);
    }
    
    public void FoundDetailsDaoDataOnDemand.setPublishyear(FoundDetailsDao obj, int index) {
        Long publishyear = new Integer(index).longValue();
        obj.setPublishyear(publishyear);
    }
    
    public void FoundDetailsDaoDataOnDemand.setSearchserviceid(FoundDetailsDao obj, int index) {
        String searchserviceid = "searchserviceid_" + index;
        obj.setSearchserviceid(searchserviceid);
    }
    
    public void FoundDetailsDaoDataOnDemand.setTitle(FoundDetailsDao obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public void FoundDetailsDaoDataOnDemand.setType(FoundDetailsDao obj, int index) {
        String type = "type_" + index;
        obj.setType(type);
    }
    
    public FoundDetailsDao FoundDetailsDaoDataOnDemand.getSpecificFoundDetailsDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FoundDetailsDao obj = data.get(index);
        Long id = obj.getId();
        return foundDetailsRepository.findOne(id);
    }
    
    public FoundDetailsDao FoundDetailsDaoDataOnDemand.getRandomFoundDetailsDao() {
        init();
        FoundDetailsDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return foundDetailsRepository.findOne(id);
    }
    
    public boolean FoundDetailsDaoDataOnDemand.modifyFoundDetailsDao(FoundDetailsDao obj) {
        return false;
    }
    
    public void FoundDetailsDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = foundDetailsRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FoundDetailsDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FoundDetailsDao>();
        for (int i = 0; i < 10; i++) {
            FoundDetailsDao obj = getNewTransientFoundDetailsDao(i);
            try {
                foundDetailsRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            foundDetailsRepository.flush();
            data.add(obj);
        }
    }
    
}
