// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.PublisherRepository;
import meg.biblio.catalog.db.dao.PublisherDao;
import meg.biblio.catalog.db.dao.PublisherDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PublisherDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PublisherDaoDataOnDemand: @Component;
    
    private Random PublisherDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<PublisherDao> PublisherDaoDataOnDemand.data;
    
    @Autowired
    PublisherRepository PublisherDaoDataOnDemand.publisherRepository;
    
    public PublisherDao PublisherDaoDataOnDemand.getNewTransientPublisherDao(int index) {
        PublisherDao obj = new PublisherDao();
        return obj;
    }
    
    public PublisherDao PublisherDaoDataOnDemand.getSpecificPublisherDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PublisherDao obj = data.get(index);
        Long id = obj.getId();
        return publisherRepository.findOne(id);
    }
    
    public PublisherDao PublisherDaoDataOnDemand.getRandomPublisherDao() {
        init();
        PublisherDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return publisherRepository.findOne(id);
    }
    
    public boolean PublisherDaoDataOnDemand.modifyPublisherDao(PublisherDao obj) {
        return false;
    }
    
    public void PublisherDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = publisherRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PublisherDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PublisherDao>();
        for (int i = 0; i < 10; i++) {
            PublisherDao obj = getNewTransientPublisherDao(i);
            try {
                publisherRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            publisherRepository.flush();
            data.add(obj);
        }
    }
    
}
