// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import meg.biblio.catalog.db.dao.PublisherDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PublisherDaoDataOnDemand_Roo_Configurable {
    
    declare @type: PublisherDaoDataOnDemand: @Configurable;
    
}
