// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.SubjectRepository;
import meg.biblio.catalog.db.dao.SubjectDao;
import meg.biblio.catalog.db.dao.SubjectDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SubjectDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SubjectDaoDataOnDemand: @Component;
    
    private Random SubjectDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<SubjectDao> SubjectDaoDataOnDemand.data;
    
    @Autowired
    SubjectRepository SubjectDaoDataOnDemand.subjectRepository;
    
    public SubjectDao SubjectDaoDataOnDemand.getNewTransientSubjectDao(int index) {
        SubjectDao obj = new SubjectDao();
        setListing(obj, index);
        return obj;
    }
    
    public void SubjectDaoDataOnDemand.setListing(SubjectDao obj, int index) {
        String listing = "listing_" + index;
        obj.setListing(listing);
    }
    
    public SubjectDao SubjectDaoDataOnDemand.getSpecificSubjectDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SubjectDao obj = data.get(index);
        Long id = obj.getId();
        return subjectRepository.findOne(id);
    }
    
    public SubjectDao SubjectDaoDataOnDemand.getRandomSubjectDao() {
        init();
        SubjectDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return subjectRepository.findOne(id);
    }
    
    public boolean SubjectDaoDataOnDemand.modifySubjectDao(SubjectDao obj) {
        return false;
    }
    
    public void SubjectDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = subjectRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SubjectDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SubjectDao>();
        for (int i = 0; i < 10; i++) {
            SubjectDao obj = getNewTransientSubjectDao(i);
            try {
                subjectRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            subjectRepository.flush();
            data.add(obj);
        }
    }
    
}
