// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.common.db.dao;

import meg.biblio.common.db.dao.ClientDao;

privileged aspect ClientDao_Roo_JavaBean {
    
    public String ClientDao.getName() {
        return this.name;
    }
    
    public void ClientDao.setName(String name) {
        this.name = name;
    }
    
}
