// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.common.db.dao;

import meg.biblio.common.db.dao.RoleDao;

privileged aspect RoleDao_Roo_JavaBean {
    
    public String RoleDao.getRolename() {
        return this.rolename;
    }
    
    public void RoleDao.setRolename(String rolename) {
        this.rolename = rolename;
    }
    
}
