// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.common.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.common.db.ClientRepository;
import meg.biblio.common.db.dao.ClientDao;
import meg.biblio.common.db.dao.ClientDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ClientDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClientDaoDataOnDemand: @Component;
    
    private Random ClientDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<ClientDao> ClientDaoDataOnDemand.data;
    
    @Autowired
    ClientRepository ClientDaoDataOnDemand.clientRepository;
    
    public ClientDao ClientDaoDataOnDemand.getNewTransientClientDao(int index) {
        ClientDao obj = new ClientDao();
        setBarcodesheetxsl(obj, index);
        setClassifyimplementation(obj, index);
        setClasssummaryxslbase(obj, index);
        setClientnr(obj, index);
        setDetailCompleteCode(obj, index);
        setImagepath(obj, index);
        setImportfileconfig(obj, index);
        setImportmapconfig(obj, index);
        setLastBcBase(obj, index);
        setLastBookNr(obj, index);
        setName(obj, index);
        setOverduexslbase(obj, index);
        setShortname(obj, index);
        setStudentCOLimit(obj, index);
        setStudentcheckouttime(obj, index);
        setTeacherCOLimit(obj, index);
        setTeachercheckouttime(obj, index);
        setUsesBarcodes(obj, index);
        return obj;
    }
    
    public void ClientDaoDataOnDemand.setBarcodesheetxsl(ClientDao obj, int index) {
        String barcodesheetxsl = "barcodesheetxsl_" + index;
        obj.setBarcodesheetxsl(barcodesheetxsl);
    }
    
    public void ClientDaoDataOnDemand.setClassifyimplementation(ClientDao obj, int index) {
        String classifyimplementation = "classifyimplementation_" + index;
        obj.setClassifyimplementation(classifyimplementation);
    }
    
    public void ClientDaoDataOnDemand.setClasssummaryxslbase(ClientDao obj, int index) {
        String classsummaryxslbase = "classsummaryxslbase_" + index;
        obj.setClasssummaryxslbase(classsummaryxslbase);
    }
    
    public void ClientDaoDataOnDemand.setClientnr(ClientDao obj, int index) {
        Long clientnr = new Integer(index).longValue();
        obj.setClientnr(clientnr);
    }
    
    public void ClientDaoDataOnDemand.setDetailCompleteCode(ClientDao obj, int index) {
        Long detailCompleteCode = new Integer(index).longValue();
        obj.setDetailCompleteCode(detailCompleteCode);
    }
    
    public void ClientDaoDataOnDemand.setImagepath(ClientDao obj, int index) {
        String imagepath = "imagepath_" + index;
        obj.setImagepath(imagepath);
    }
    
    public void ClientDaoDataOnDemand.setImportfileconfig(ClientDao obj, int index) {
        String importfileconfig = "importfileconfig_" + index;
        obj.setImportfileconfig(importfileconfig);
    }
    
    public void ClientDaoDataOnDemand.setImportmapconfig(ClientDao obj, int index) {
        String importmapconfig = "importmapconfig_" + index;
        obj.setImportmapconfig(importmapconfig);
    }
    
    public void ClientDaoDataOnDemand.setLastBcBase(ClientDao obj, int index) {
        Long lastBcBase = new Integer(index).longValue();
        obj.setLastBcBase(lastBcBase);
    }
    
    public void ClientDaoDataOnDemand.setLastBookNr(ClientDao obj, int index) {
        Long lastBookNr = new Integer(index).longValue();
        obj.setLastBookNr(lastBookNr);
    }
    
    public void ClientDaoDataOnDemand.setName(ClientDao obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ClientDaoDataOnDemand.setOverduexslbase(ClientDao obj, int index) {
        String overduexslbase = "overduexslbase_" + index;
        obj.setOverduexslbase(overduexslbase);
    }
    
    public void ClientDaoDataOnDemand.setShortname(ClientDao obj, int index) {
        String shortname = "shortname_" + index;
        obj.setShortname(shortname);
    }
    
    public void ClientDaoDataOnDemand.setStudentCOLimit(ClientDao obj, int index) {
        Integer studentCOLimit = new Integer(index);
        obj.setStudentCOLimit(studentCOLimit);
    }
    
    public void ClientDaoDataOnDemand.setStudentcheckouttime(ClientDao obj, int index) {
        Integer studentcheckouttime = new Integer(index);
        obj.setStudentcheckouttime(studentcheckouttime);
    }
    
    public void ClientDaoDataOnDemand.setTeacherCOLimit(ClientDao obj, int index) {
        Integer teacherCOLimit = new Integer(index);
        obj.setTeacherCOLimit(teacherCOLimit);
    }
    
    public void ClientDaoDataOnDemand.setTeachercheckouttime(ClientDao obj, int index) {
        Integer teachercheckouttime = new Integer(index);
        obj.setTeachercheckouttime(teachercheckouttime);
    }
    
    public void ClientDaoDataOnDemand.setUsesBarcodes(ClientDao obj, int index) {
        Boolean usesBarcodes = Boolean.TRUE;
        obj.setUsesBarcodes(usesBarcodes);
    }
    
    public ClientDao ClientDaoDataOnDemand.getSpecificClientDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ClientDao obj = data.get(index);
        Long id = obj.getId();
        return clientRepository.findOne(id);
    }
    
    public ClientDao ClientDaoDataOnDemand.getRandomClientDao() {
        init();
        ClientDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return clientRepository.findOne(id);
    }
    
    public boolean ClientDaoDataOnDemand.modifyClientDao(ClientDao obj) {
        return false;
    }
    
    public void ClientDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = clientRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ClientDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ClientDao>();
        for (int i = 0; i < 10; i++) {
            ClientDao obj = getNewTransientClientDao(i);
            try {
                clientRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            clientRepository.flush();
            data.add(obj);
        }
    }
    
}
