// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.common.db.dao;

import meg.biblio.common.db.dao.ImportBookDaoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ImportBookDaoIntegrationTest_Roo_Configurable {
    
    declare @type: ImportBookDaoIntegrationTest: @Configurable;
    
}
