// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.common.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.common.db.SelectValueRepository;
import meg.biblio.common.db.dao.SelectKeyDaoDataOnDemand;
import meg.biblio.common.db.dao.SelectValueDao;
import meg.biblio.common.db.dao.SelectValueDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SelectValueDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SelectValueDaoDataOnDemand: @Component;
    
    private Random SelectValueDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<SelectValueDao> SelectValueDaoDataOnDemand.data;
    
    @Autowired
    SelectKeyDaoDataOnDemand SelectValueDaoDataOnDemand.selectKeyDaoDataOnDemand;
    
    @Autowired
    SelectValueRepository SelectValueDaoDataOnDemand.selectValueRepository;
    
    public SelectValueDao SelectValueDaoDataOnDemand.getNewTransientSelectValueDao(int index) {
        SelectValueDao obj = new SelectValueDao();
        setActive(obj, index);
        setDisplay(obj, index);
        setDisporder(obj, index);
        setLanguagekey(obj, index);
        setValue(obj, index);
        return obj;
    }
    
    public void SelectValueDaoDataOnDemand.setActive(SelectValueDao obj, int index) {
        Boolean active = Boolean.TRUE;
        obj.setActive(active);
    }
    
    public void SelectValueDaoDataOnDemand.setDisplay(SelectValueDao obj, int index) {
        String display = "display_" + index;
        if (display.length() > 100) {
            display = display.substring(0, 100);
        }
        obj.setDisplay(display);
    }
    
    public void SelectValueDaoDataOnDemand.setDisporder(SelectValueDao obj, int index) {
        Long disporder = new Integer(index).longValue();
        obj.setDisporder(disporder);
    }
    
    public void SelectValueDaoDataOnDemand.setLanguagekey(SelectValueDao obj, int index) {
        String languagekey = "languagekey_" + index;
        obj.setLanguagekey(languagekey);
    }
    
    public void SelectValueDaoDataOnDemand.setValue(SelectValueDao obj, int index) {
        String value = "value_" + index;
        if (value.length() > 100) {
            value = value.substring(0, 100);
        }
        obj.setValue(value);
    }
    
    public SelectValueDao SelectValueDaoDataOnDemand.getSpecificSelectValueDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SelectValueDao obj = data.get(index);
        Long id = obj.getId();
        return selectValueRepository.findOne(id);
    }
    
    public SelectValueDao SelectValueDaoDataOnDemand.getRandomSelectValueDao() {
        init();
        SelectValueDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return selectValueRepository.findOne(id);
    }
    
    public boolean SelectValueDaoDataOnDemand.modifySelectValueDao(SelectValueDao obj) {
        return false;
    }
    
    public void SelectValueDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = selectValueRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SelectValueDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SelectValueDao>();
        for (int i = 0; i < 10; i++) {
            SelectValueDao obj = getNewTransientSelectValueDao(i);
            try {
                selectValueRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            selectValueRepository.flush();
            data.add(obj);
        }
    }
    
}
