// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db;

import meg.biblio.catalog.db.IgnoredWordsDao;

privileged aspect IgnoredWordsDao_Roo_JavaBean {
    
    public String IgnoredWordsDao.getWord() {
        return this.word;
    }
    
    public void IgnoredWordsDao.setWord(String word) {
        this.word = word;
    }
    
}
