// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.lending.db.dao;

import meg.biblio.lending.db.dao.LoanHistoryDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LoanHistoryDaoDataOnDemand_Roo_Configurable {
    
    declare @type: LoanHistoryDaoDataOnDemand: @Configurable;
    
}
