// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.lending.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.dao.BookDaoDataOnDemand;
import meg.biblio.common.db.dao.ClientDaoDataOnDemand;
import meg.biblio.lending.db.LoanHistoryRepository;
import meg.biblio.lending.db.dao.LoanHistoryDao;
import meg.biblio.lending.db.dao.LoanHistoryDaoDataOnDemand;
import meg.biblio.lending.db.dao.PersonDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LoanHistoryDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LoanHistoryDaoDataOnDemand: @Component;
    
    private Random LoanHistoryDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<LoanHistoryDao> LoanHistoryDaoDataOnDemand.data;
    
    @Autowired
    BookDaoDataOnDemand LoanHistoryDaoDataOnDemand.bookDaoDataOnDemand;
    
    @Autowired
    PersonDaoDataOnDemand LoanHistoryDaoDataOnDemand.personDaoDataOnDemand;
    
    @Autowired
    ClientDaoDataOnDemand LoanHistoryDaoDataOnDemand.clientDaoDataOnDemand;
    
    @Autowired
    LoanHistoryRepository LoanHistoryDaoDataOnDemand.loanHistoryRepository;
    
    public LoanHistoryDao LoanHistoryDaoDataOnDemand.getNewTransientLoanHistoryDao(int index) {
        LoanHistoryDao obj = new LoanHistoryDao();
        setCheckedout(obj, index);
        setDuedate(obj, index);
        setReturned(obj, index);
        setSchoolyear(obj, index);
        setTeachername(obj, index);
        return obj;
    }
    
    public void LoanHistoryDaoDataOnDemand.setCheckedout(LoanHistoryDao obj, int index) {
        Date checkedout = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCheckedout(checkedout);
    }
    
    public void LoanHistoryDaoDataOnDemand.setDuedate(LoanHistoryDao obj, int index) {
        Date duedate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDuedate(duedate);
    }
    
    public void LoanHistoryDaoDataOnDemand.setReturned(LoanHistoryDao obj, int index) {
        Date returned = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setReturned(returned);
    }
    
    public void LoanHistoryDaoDataOnDemand.setSchoolyear(LoanHistoryDao obj, int index) {
        String schoolyear = "schoolyear_" + index;
        obj.setSchoolyear(schoolyear);
    }
    
    public void LoanHistoryDaoDataOnDemand.setTeachername(LoanHistoryDao obj, int index) {
        String teachername = "teachername_" + index;
        obj.setTeachername(teachername);
    }
    
    public LoanHistoryDao LoanHistoryDaoDataOnDemand.getSpecificLoanHistoryDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LoanHistoryDao obj = data.get(index);
        Long id = obj.getId();
        return loanHistoryRepository.findOne(id);
    }
    
    public LoanHistoryDao LoanHistoryDaoDataOnDemand.getRandomLoanHistoryDao() {
        init();
        LoanHistoryDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return loanHistoryRepository.findOne(id);
    }
    
    public boolean LoanHistoryDaoDataOnDemand.modifyLoanHistoryDao(LoanHistoryDao obj) {
        return false;
    }
    
    public void LoanHistoryDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = loanHistoryRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LoanHistoryDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LoanHistoryDao>();
        for (int i = 0; i < 10; i++) {
            LoanHistoryDao obj = getNewTransientLoanHistoryDao(i);
            try {
                loanHistoryRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            loanHistoryRepository.flush();
            data.add(obj);
        }
    }
    
}
