// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.lending.db.dao;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.lending.db.LoanHistoryRepository;
import meg.biblio.lending.db.dao.LoanHistoryDaoDataOnDemand;
import meg.biblio.lending.db.dao.LoanHistoryDaoIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LoanHistoryDaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LoanHistoryDaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LoanHistoryDaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LoanHistoryDaoIntegrationTest: @Transactional;
    
    @Autowired
    LoanHistoryDaoDataOnDemand LoanHistoryDaoIntegrationTest.dod;
    
    @Autowired
    LoanHistoryRepository LoanHistoryDaoIntegrationTest.loanHistoryRepository;
    
    @Test
    public void LoanHistoryDaoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to initialize correctly", dod.getRandomLoanHistoryDao());
        long count = loanHistoryRepository.count();
        Assert.assertTrue("Counter for 'LoanHistoryDao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LoanHistoryDaoIntegrationTest.testFind() {
        LoanHistoryDao obj = dod.getRandomLoanHistoryDao();
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to provide an identifier", id);
        obj = loanHistoryRepository.findOne(id);
        Assert.assertNotNull("Find method for 'LoanHistoryDao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LoanHistoryDao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LoanHistoryDaoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to initialize correctly", dod.getRandomLoanHistoryDao());
        long count = loanHistoryRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'LoanHistoryDao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LoanHistoryDao> result = loanHistoryRepository.findAll();
        Assert.assertNotNull("Find all method for 'LoanHistoryDao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LoanHistoryDao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LoanHistoryDaoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to initialize correctly", dod.getRandomLoanHistoryDao());
        long count = loanHistoryRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LoanHistoryDao> result = loanHistoryRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'LoanHistoryDao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LoanHistoryDao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LoanHistoryDaoIntegrationTest.testFlush() {
        LoanHistoryDao obj = dod.getRandomLoanHistoryDao();
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to provide an identifier", id);
        obj = loanHistoryRepository.findOne(id);
        Assert.assertNotNull("Find method for 'LoanHistoryDao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLoanHistoryDao(obj);
        Integer currentVersion = obj.getVersion();
        loanHistoryRepository.flush();
        Assert.assertTrue("Version for 'LoanHistoryDao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LoanHistoryDaoIntegrationTest.testSaveUpdate() {
        LoanHistoryDao obj = dod.getRandomLoanHistoryDao();
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to provide an identifier", id);
        obj = loanHistoryRepository.findOne(id);
        boolean modified =  dod.modifyLoanHistoryDao(obj);
        Integer currentVersion = obj.getVersion();
        LoanHistoryDao merged = loanHistoryRepository.save(obj);
        loanHistoryRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LoanHistoryDao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LoanHistoryDaoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to initialize correctly", dod.getRandomLoanHistoryDao());
        LoanHistoryDao obj = dod.getNewTransientLoanHistoryDao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LoanHistoryDao' identifier to be null", obj.getId());
        try {
            loanHistoryRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        loanHistoryRepository.flush();
        Assert.assertNotNull("Expected 'LoanHistoryDao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LoanHistoryDaoIntegrationTest.testDelete() {
        LoanHistoryDao obj = dod.getRandomLoanHistoryDao();
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LoanHistoryDao' failed to provide an identifier", id);
        obj = loanHistoryRepository.findOne(id);
        loanHistoryRepository.delete(obj);
        loanHistoryRepository.flush();
        Assert.assertNull("Failed to remove 'LoanHistoryDao' with identifier '" + id + "'", loanHistoryRepository.findOne(id));
    }
    
}
