// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.lending.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.common.db.dao.ClientDaoDataOnDemand;
import meg.biblio.lending.db.PersonRepository;
import meg.biblio.lending.db.dao.PersonDao;
import meg.biblio.lending.db.dao.PersonDaoDataOnDemand;
import meg.biblio.lending.db.dao.SchoolGroupDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PersonDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PersonDaoDataOnDemand: @Component;
    
    private Random PersonDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<PersonDao> PersonDaoDataOnDemand.data;
    
    @Autowired
    ClientDaoDataOnDemand PersonDaoDataOnDemand.clientDaoDataOnDemand;
    
    @Autowired
    SchoolGroupDaoDataOnDemand PersonDaoDataOnDemand.schoolGroupDaoDataOnDemand;
    
    @Autowired
    PersonRepository PersonDaoDataOnDemand.personRepository;
    
    public PersonDao PersonDaoDataOnDemand.getNewTransientPersonDao(int index) {
        PersonDao obj = new PersonDao();
        setFirstname(obj, index);
        setLastname(obj, index);
        return obj;
    }
    
    public void PersonDaoDataOnDemand.setFirstname(PersonDao obj, int index) {
        String firstname = "firstname_" + index;
        obj.setFirstname(firstname);
    }
    
    public void PersonDaoDataOnDemand.setLastname(PersonDao obj, int index) {
        String lastname = "lastname_" + index;
        obj.setLastname(lastname);
    }
    
    public PersonDao PersonDaoDataOnDemand.getSpecificPersonDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PersonDao obj = data.get(index);
        Long id = obj.getId();
        return personRepository.findOne(id);
    }
    
    public PersonDao PersonDaoDataOnDemand.getRandomPersonDao() {
        init();
        PersonDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return personRepository.findOne(id);
    }
    
    public boolean PersonDaoDataOnDemand.modifyPersonDao(PersonDao obj) {
        return false;
    }
    
    public void PersonDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = personRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PersonDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PersonDao>();
        for (int i = 0; i < 10; i++) {
            PersonDao obj = getNewTransientPersonDao(i);
            try {
                personRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            personRepository.flush();
            data.add(obj);
        }
    }
    
}
