// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.lending.db.dao;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.lending.db.SchoolGroupRepository;
import meg.biblio.lending.db.dao.SchoolGroupDaoDataOnDemand;
import meg.biblio.lending.db.dao.SchoolGroupDaoIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolGroupDaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolGroupDaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolGroupDaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolGroupDaoIntegrationTest: @Transactional;
    
    @Autowired
    SchoolGroupDaoDataOnDemand SchoolGroupDaoIntegrationTest.dod;
    
    @Autowired
    SchoolGroupRepository SchoolGroupDaoIntegrationTest.schoolGroupRepository;
    
    @Test
    public void SchoolGroupDaoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to initialize correctly", dod.getRandomSchoolGroupDao());
        long count = schoolGroupRepository.count();
        Assert.assertTrue("Counter for 'SchoolGroupDao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolGroupDaoIntegrationTest.testFind() {
        SchoolGroupDao obj = dod.getRandomSchoolGroupDao();
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to provide an identifier", id);
        obj = schoolGroupRepository.findOne(id);
        Assert.assertNotNull("Find method for 'SchoolGroupDao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolGroupDao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SchoolGroupDaoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to initialize correctly", dod.getRandomSchoolGroupDao());
        long count = schoolGroupRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolGroupDao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolGroupDao> result = schoolGroupRepository.findAll();
        Assert.assertNotNull("Find all method for 'SchoolGroupDao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolGroupDao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolGroupDaoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to initialize correctly", dod.getRandomSchoolGroupDao());
        long count = schoolGroupRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolGroupDao> result = schoolGroupRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'SchoolGroupDao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolGroupDao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolGroupDaoIntegrationTest.testFlush() {
        SchoolGroupDao obj = dod.getRandomSchoolGroupDao();
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to provide an identifier", id);
        obj = schoolGroupRepository.findOne(id);
        Assert.assertNotNull("Find method for 'SchoolGroupDao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySchoolGroupDao(obj);
        Integer currentVersion = obj.getVersion();
        schoolGroupRepository.flush();
        Assert.assertTrue("Version for 'SchoolGroupDao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SchoolGroupDaoIntegrationTest.testSaveUpdate() {
        SchoolGroupDao obj = dod.getRandomSchoolGroupDao();
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to provide an identifier", id);
        obj = schoolGroupRepository.findOne(id);
        boolean modified =  dod.modifySchoolGroupDao(obj);
        Integer currentVersion = obj.getVersion();
        SchoolGroupDao merged = schoolGroupRepository.save(obj);
        schoolGroupRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SchoolGroupDao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SchoolGroupDaoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to initialize correctly", dod.getRandomSchoolGroupDao());
        SchoolGroupDao obj = dod.getNewTransientSchoolGroupDao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolGroupDao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolGroupDao' identifier to be null", obj.getId());
        try {
            schoolGroupRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        schoolGroupRepository.flush();
        Assert.assertNotNull("Expected 'SchoolGroupDao' identifier to no longer be null", obj.getId());
    }
    
}
