// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.inventory.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.inventory.db.InventoryHistRepository;
import meg.biblio.inventory.db.dao.InventoryHistoryDao;
import meg.biblio.inventory.db.dao.InventoryHistoryDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect InventoryHistoryDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InventoryHistoryDaoDataOnDemand: @Component;
    
    private Random InventoryHistoryDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<InventoryHistoryDao> InventoryHistoryDaoDataOnDemand.data;
    
    @Autowired
    InventoryHistRepository InventoryHistoryDaoDataOnDemand.inventoryHistRepository;
    
    public InventoryHistoryDao InventoryHistoryDaoDataOnDemand.getNewTransientInventoryHistoryDao(int index) {
        InventoryHistoryDao obj = new InventoryHistoryDao();
        return obj;
    }
    
    public InventoryHistoryDao InventoryHistoryDaoDataOnDemand.getSpecificInventoryHistoryDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        InventoryHistoryDao obj = data.get(index);
        Long id = obj.getId();
        return inventoryHistRepository.findOne(id);
    }
    
    public InventoryHistoryDao InventoryHistoryDaoDataOnDemand.getRandomInventoryHistoryDao() {
        init();
        InventoryHistoryDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return inventoryHistRepository.findOne(id);
    }
    
    public boolean InventoryHistoryDaoDataOnDemand.modifyInventoryHistoryDao(InventoryHistoryDao obj) {
        return false;
    }
    
    public void InventoryHistoryDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = inventoryHistRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'InventoryHistoryDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<InventoryHistoryDao>();
        for (int i = 0; i < 10; i++) {
            InventoryHistoryDao obj = getNewTransientInventoryHistoryDao(i);
            try {
                inventoryHistRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            inventoryHistRepository.flush();
            data.add(obj);
        }
    }
    
}
