// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.inventory.db.dao;

import meg.biblio.inventory.db.dao.InventoryDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect InventoryDaoDataOnDemand_Roo_Configurable {
    
    declare @type: InventoryDaoDataOnDemand: @Configurable;
    
}
