// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.inventory.db.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.inventory.db.InventoryRepository;
import meg.biblio.inventory.db.dao.InventoryDao;
import meg.biblio.inventory.db.dao.InventoryDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect InventoryDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InventoryDaoDataOnDemand: @Component;
    
    private Random InventoryDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<InventoryDao> InventoryDaoDataOnDemand.data;
    
    @Autowired
    InventoryRepository InventoryDaoDataOnDemand.inventoryRepository;
    
    public InventoryDao InventoryDaoDataOnDemand.getNewTransientInventoryDao(int index) {
        InventoryDao obj = new InventoryDao();
        setAddedtocount(obj, index);
        setClientid(obj, index);
        setCompleted(obj, index);
        setEnddate(obj, index);
        setReconciled(obj, index);
        setStartdate(obj, index);
        setTobecounted(obj, index);
        setTotalcounted(obj, index);
        return obj;
    }
    
    public void InventoryDaoDataOnDemand.setAddedtocount(InventoryDao obj, int index) {
        Integer addedtocount = new Integer(index);
        obj.setAddedtocount(addedtocount);
    }
    
    public void InventoryDaoDataOnDemand.setClientid(InventoryDao obj, int index) {
        Long clientid = new Integer(index).longValue();
        obj.setClientid(clientid);
    }
    
    public void InventoryDaoDataOnDemand.setCompleted(InventoryDao obj, int index) {
        Boolean completed = Boolean.TRUE;
        obj.setCompleted(completed);
    }
    
    public void InventoryDaoDataOnDemand.setEnddate(InventoryDao obj, int index) {
        Date enddate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEnddate(enddate);
    }
    
    public void InventoryDaoDataOnDemand.setReconciled(InventoryDao obj, int index) {
        Integer reconciled = new Integer(index);
        obj.setReconciled(reconciled);
    }
    
    public void InventoryDaoDataOnDemand.setStartdate(InventoryDao obj, int index) {
        Date startdate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartdate(startdate);
    }
    
    public void InventoryDaoDataOnDemand.setTobecounted(InventoryDao obj, int index) {
        Integer tobecounted = new Integer(index);
        obj.setTobecounted(tobecounted);
    }
    
    public void InventoryDaoDataOnDemand.setTotalcounted(InventoryDao obj, int index) {
        Integer totalcounted = new Integer(index);
        obj.setTotalcounted(totalcounted);
    }
    
    public InventoryDao InventoryDaoDataOnDemand.getSpecificInventoryDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        InventoryDao obj = data.get(index);
        Long id = obj.getId();
        return inventoryRepository.findOne(id);
    }
    
    public InventoryDao InventoryDaoDataOnDemand.getRandomInventoryDao() {
        init();
        InventoryDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return inventoryRepository.findOne(id);
    }
    
    public boolean InventoryDaoDataOnDemand.modifyInventoryDao(InventoryDao obj) {
        return false;
    }
    
    public void InventoryDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = inventoryRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'InventoryDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<InventoryDao>();
        for (int i = 0; i < 10; i++) {
            InventoryDao obj = getNewTransientInventoryDao(i);
            try {
                inventoryRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            inventoryRepository.flush();
            data.add(obj);
        }
    }
    
}
