// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import meg.biblio.catalog.db.dao.PublisherDao;

privileged aspect PublisherDao_Roo_JavaBean {
    
    public String PublisherDao.getName() {
        return this.name;
    }
    
    public void PublisherDao.setName(String name) {
        this.name = name;
    }
    
}
