// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db.dao;

import meg.biblio.catalog.db.dao.SubjectDao;

privileged aspect SubjectDao_Roo_JavaBean {
    
    public String SubjectDao.getListing() {
        return this.listing;
    }
    
    public void SubjectDao.setListing(String listing) {
        this.listing = listing;
    }
    
}
