// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.lending.db.dao;

import meg.biblio.lending.db.dao.StudentDao;

privileged aspect StudentDao_Roo_JavaBean {
    
    public Long StudentDao.getSectionkey() {
        return this.sectionkey;
    }
    
    public void StudentDao.setSectionkey(Long sectionkey) {
        this.sectionkey = sectionkey;
    }
    
}
