// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.lending.db.dao;

import javax.persistence.Entity;
import meg.biblio.lending.db.dao.StudentDao;

privileged aspect StudentDao_Roo_Jpa_Entity {
    
    declare @type: StudentDao: @Entity;
    
}
