// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.lending.db.dao;

import meg.biblio.lending.db.dao.TeacherDao;

privileged aspect TeacherDao_Roo_JavaBean {
    
    public String TeacherDao.getEmail() {
        return this.email;
    }
    
    public void TeacherDao.setEmail(String email) {
        this.email = email;
    }
    
}
