// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.biblio.catalog.db;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.biblio.catalog.db.IgnoredWordsDaoDataOnDemand;
import meg.biblio.catalog.db.IgnoredWordsDaoIntegrationTest;
import meg.biblio.catalog.db.IgnoredWordsRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IgnoredWordsDaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IgnoredWordsDaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IgnoredWordsDaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: IgnoredWordsDaoIntegrationTest: @Transactional;
    
    @Autowired
    IgnoredWordsDaoDataOnDemand IgnoredWordsDaoIntegrationTest.dod;
    
    @Autowired
    IgnoredWordsRepository IgnoredWordsDaoIntegrationTest.ignoredWordsRepository;
    
    @Test
    public void IgnoredWordsDaoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to initialize correctly", dod.getRandomIgnoredWordsDao());
        long count = ignoredWordsRepository.count();
        Assert.assertTrue("Counter for 'IgnoredWordsDao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IgnoredWordsDaoIntegrationTest.testFind() {
        IgnoredWordsDao obj = dod.getRandomIgnoredWordsDao();
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to provide an identifier", id);
        obj = ignoredWordsRepository.findOne(id);
        Assert.assertNotNull("Find method for 'IgnoredWordsDao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'IgnoredWordsDao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IgnoredWordsDaoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to initialize correctly", dod.getRandomIgnoredWordsDao());
        long count = ignoredWordsRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'IgnoredWordsDao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<IgnoredWordsDao> result = ignoredWordsRepository.findAll();
        Assert.assertNotNull("Find all method for 'IgnoredWordsDao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'IgnoredWordsDao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IgnoredWordsDaoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to initialize correctly", dod.getRandomIgnoredWordsDao());
        long count = ignoredWordsRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<IgnoredWordsDao> result = ignoredWordsRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'IgnoredWordsDao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'IgnoredWordsDao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IgnoredWordsDaoIntegrationTest.testFlush() {
        IgnoredWordsDao obj = dod.getRandomIgnoredWordsDao();
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to provide an identifier", id);
        obj = ignoredWordsRepository.findOne(id);
        Assert.assertNotNull("Find method for 'IgnoredWordsDao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIgnoredWordsDao(obj);
        Integer currentVersion = obj.getVersion();
        ignoredWordsRepository.flush();
        Assert.assertTrue("Version for 'IgnoredWordsDao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IgnoredWordsDaoIntegrationTest.testSaveUpdate() {
        IgnoredWordsDao obj = dod.getRandomIgnoredWordsDao();
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to provide an identifier", id);
        obj = ignoredWordsRepository.findOne(id);
        boolean modified =  dod.modifyIgnoredWordsDao(obj);
        Integer currentVersion = obj.getVersion();
        IgnoredWordsDao merged = ignoredWordsRepository.save(obj);
        ignoredWordsRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'IgnoredWordsDao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IgnoredWordsDaoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to initialize correctly", dod.getRandomIgnoredWordsDao());
        IgnoredWordsDao obj = dod.getNewTransientIgnoredWordsDao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'IgnoredWordsDao' identifier to be null", obj.getId());
        try {
            ignoredWordsRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ignoredWordsRepository.flush();
        Assert.assertNotNull("Expected 'IgnoredWordsDao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IgnoredWordsDaoIntegrationTest.testDelete() {
        IgnoredWordsDao obj = dod.getRandomIgnoredWordsDao();
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IgnoredWordsDao' failed to provide an identifier", id);
        obj = ignoredWordsRepository.findOne(id);
        ignoredWordsRepository.delete(obj);
        ignoredWordsRepository.flush();
        Assert.assertNull("Failed to remove 'IgnoredWordsDao' with identifier '" + id + "'", ignoredWordsRepository.findOne(id));
    }
    
}
